language:
  - ruby

rvm:
  - "1.9.3"
  - "2.0.0"

before_install:
  - cp script/ci/katello.yml config/katello.yml

install:
  - travis_retry bundle install --without devboost:optional:debugging

script:
  - "./script/ci/katello_pr_$JOB.sh"

env:
  - JOB=rspec
  - JOB=other
  - JOB=javascript
