language:
  - ruby

rvm:
  - "1.9.3"

before_install:
  - touch config/katello.yml

install:
  - bundle install --without devboost:optional:debugging

script:
  - "./script/ci/katello_pr_$JOB.sh"

env:
  - JOB=minitest
  - JOB=rspec
  - JOB=headpin_rspec
  - JOB=other
  - JOB=javascript
