--- 
pid: tmp/pids/thin.pid
address: 127.0.0.1
wait: 30
timeout: 30
port: 5000
log: /var/log/katello/thin-log.log
max_conns: 1024
require: []

max_persistent_conns: 512
servers: 4
daemonize: yes
chdir: /usr/share/katello
