embed_assets: datauri
javascript_compressor: yui
compress_assets: on
gzip_assets: on

javascripts:
  common:
    - public/javascripts/vendor/jquery/jquery-1.6.2.js
    - public/javascripts/vendor/underscore-1.3.1.js
    - public/javascripts/vendor/jquery-ui-1.8.11.custom/js/jquery-ui-1.8.11.custom.min.js
    - public/javascripts/vendor/jquery/plugins/jquery.hoverIntent.js
    - public/javascripts/vendor/jquery/plugins/jquery.ui.totop.js
    - public/javascripts/vendor/rails.js
    - public/javascripts/vendor/jquery/plugins/jquery.jnotify.js
    - public/javascripts/vendor/jquery/plugins/jquery.text-overflow.js
    - public/javascripts/katello.js
    - public/javascripts/menu.js
    - public/javascripts/routes.js
    - public/javascripts/vendor/jquery/plugins/jquery.linkHover.js
    - public/javascripts/vendor/jquery/plugins/jquery.sparkline.min.js
    - public/javascripts/vendor/jquery/plugins/jquery.mousewheel.js
    - public/javascripts/vendor/jquery/plugins/jquery.jscrollpane.js
    - public/javascripts/vendor/jquery/plugins/jquery.ba-bbq.js
    - public/javascripts/vendor/jquery/plugins/jquery.tipsy.js
    #edit
    - public/javascripts/vendor/jquery/plugins/jquery.jeditable.js
    - public/javascripts/vendor/jquery/plugins/jquery.jeditable.ajaxupload.js
    - public/javascripts/vendor/jquery/plugins/jquery.ajaxfileupload.js
    - public/javascripts/jquery.jeditable.custominputs.js
    #panel
    - public/javascripts/vendor/jquery/plugins/jquery.fancyqueries.js
    - public/javascripts/vendor/jquery/plugins/jquery.ba-resize.js
    - public/javascripts/search.js
    - public/javascripts/panel.js
    - public/javascripts/katello_object.js
    #form
    - public/javascripts/vendor/jquery/plugins/jquery.form.js
    #notices:
    - public/javascripts/notices.js
    - public/javascripts/vendor/jquery/plugins/jquery.periodicalupdater.js
    #tipsycustom
    - public/javascripts/widgets/tipsy.custom.js
    #env_select
    - public/javascripts/widgets/path_selector.js
    #old env_select
    - public/javascripts/env_select_scroll.js
    - public/javascripts/env_select.js
  html5:
    - public/javascripts/html5.js
    - public/javascripts/excanvas.js
  activation_key:
    - public/javascripts/activation_key.js
    - public/javascripts/system_groups_pane.js
    - public/javascripts/vendor/jquery/plugins/jquery.multiselect.js
    - public/javascripts/vendor/jquery/plugins/jquery.multiselect.filter.js
  activation_key_edit:
    - public/javascripts/activation_key_edit.js
  activation_key_subscriptions:
    - public/javascripts/activation_key_subscriptions.js
  architecture:
    - public/javascripts/architecture.js
    - public/javascripts/chosen.jquery.js
  domain:
    - public/javascripts/domain.js
    - public/javascripts/chosen.jquery.js
  gpg_key:
    - public/javascripts/gpg_key.js
  gpg_key_edit:
    - public/javascripts/gpg_key_edit.js
  content:
    - public/javascripts/vendor/jquery/plugins/jquery.treeTable.js
    - public/javascripts/content.js
    - public/javascripts/vendor/jquery/plugins/jquery.periodicalupdater.js
  dashboard:
    - public/javascripts/vendor/jquery/plugins/flot-0.7/jquery.flot.js
    - public/javascripts/vendor/jquery/plugins/flot-0.7/jquery.flot.pie.js
    - public/javascripts/dashboard.js
  plan:
    - public/javascripts/plan.js
    - public/javascripts/vendor/jquery/plugins/jquery.timepickr.js
  plan_edit:
    - public/javascripts/plan_edit.js
  filters:
    - public/javascripts/filters.js
    - public/javascripts/vendor/jquery/plugins/jquery.sortElements.js
    - public/javascripts/auto_complete.js
    - public/javascripts/chosen.jquery.js
  promotion:
    - public/javascripts/promotion.js
    - public/javascripts/vendor/jquery/plugins/jquery.sortElements.js
    - public/javascripts/slidingtree.js
  changeset:
    - public/javascripts/changeset.js
  changeset_edit:
    - public/javascripts/changeset_edit.js
  content_search:
    - public/javascripts/chosen.jquery.js
    - public/javascripts/widgets/comparison_grid.js
    - public/javascripts/content_search.js
    - public/javascripts/auto_complete.js
    - public/javascripts/vendor/jquery/plugins/jquery.trunk8.js
  smart_proxy:
    - public/javascripts/smart_proxy.js
  subnet:
    - public/javascripts/subnet.js
    - public/javascripts/chosen.jquery.js
    - public/javascripts/vendor/jquery/plugins/jquery.multiselect.js
  subscription:
    - public/javascripts/subscription.js
    - public/javascripts/headpin.sparkline.js
  system:
    - public/javascripts/packages.js
    - public/javascripts/systems.js
    - public/javascripts/vendor/jquery/plugins/ui.spinner.js
    - public/javascripts/system_errata.js
    - public/javascripts/system_groups_pane.js
    - public/javascripts/vendor/jquery/plugins/jquery.sortElements.js
    - public/javascripts/vendor/jquery/plugins/ui.spinner.js
    - public/javascripts/auto_complete.js
    - public/javascripts/vendor/jquery/plugins/jquery.multiselect.js
    - public/javascripts/vendor/jquery/plugins/jquery.multiselect.filter.js
    - public/javascripts/vendor/jquery/plugins/chosen.jquery.js
  system_edit:
    - public/javascripts/system_edit.js
  system_events:
    - public/javascripts/system_events.js
  system_groups:
    - public/javascripts/system_groups.js
    - public/javascripts/system_group_events.js
    - public/javascripts/system_errata.js
    - public/javascripts/packages.js
    - public/javascripts/package_actions.js
    - public/javascripts/auto_complete.js
  system_subscriptions:
    - public/javascripts/system_subscriptions.js
  system_packages:
    - public/javascripts/system_packages.js
  system_products:
    - public/javascripts/system_products.js
  system_template:
    - public/javascripts/slidingtree.js
    - public/javascripts/auto_complete.js
    - public/javascripts/system_template.js
    - public/javascripts/vendor/jquery/plugins/jquery.form.js
    - public/javascripts/vendor/jquery/plugins/jquery.sortElements.js
  system_template_promotion:
    - public/javascripts/system_template_promotions.js
  organization:
    - public/javascripts/organization.js
    - public/javascripts/env_select_scroll.js
  environment_edit:
    - public/javascripts/environment_edit.js
  one_panel:
    - public/javascripts/one_panel.js
  subpanel_new:
    - public/javascripts/subpanel_new.js
  product_edit:
    - public/javascripts/product_edit.js
  products_repos:
    - public/javascripts/products_repos.js
  provider:
    - public/javascripts/provider.js
    - public/javascripts/vendor/jquery/plugins/jquery.treeTable.js
  provider_redhat:
    - public/javascripts/provider_redhat.js
  provider_create:
    - public/javascripts/provider_create.js
  notices:
    - public/javascripts/notices.js
    - public/javascripts/vendor/jquery/plugins/jquery.periodicalupdater.js
  notices_list:
    - public/javascripts/notices_list.js
  user:
    - public/javascripts/user_methods.js
    - public/javascripts/user.js
  role:
    - public/javascripts/role.js
    - public/javascripts/slidingtree.js
    - public/javascripts/role_sliding_tree.js
    - public/javascripts/vendor/jquery/plugins/jquery.sortElements.js
  role_edit:
    - public/javascripts/role_edit.js
  sync_schedule:
    - public/javascripts/sync_schedule.js
  edit_helpers:
    - public/javascripts/jquery.jeditable.helpers.js
  treetable:
    - public/javascripts/vendor/jquery/plugins/jquery.treeTable.js
  multiselect:
    - public/javascripts/vendor/jquery/plugins/jquery.ui.multiselect.js
  filtertable:
    - public/javascripts/vendor/jquery/plugins/jquery.uitablefilter.js
    - public/javascripts/filtertable.js
  packages_filtertable:
    - public/javascripts/vendor/jquery/plugins/jquery.uitablefilter.js
    - public/javascripts/packages_filtertable.js
  scroll_pane:
    - public/javascripts/scroll_pane.js
  tabs:
    - public/javascripts/tabs.js
  alchemy:
    - public/javascripts/alchemy/login.js
    - public/javascripts/alchemy/password.js

stylesheets:
  common:
    - public/javascripts/vendor/jquery-ui-1.8.11.custom/css/custom-theme/jquery-ui-1.8.11.custom.css
    - public/stylesheets/jquery.loadmask.css
    - public/stylesheets/jquery.jnotify.css
    - public/stylesheets/jquery.treeTable.css
    - public/stylesheets/jquery.jscrollpane.css
    - public/stylesheets/jquery.tipsy.css
    - public/stylesheets/compiled/widgets/tipsy_custom.css
    - public/stylesheets/compiled/widgets/path_selector.css
    - public/stylesheets/compiled/fancyqueries.css
    - public/stylesheets/compiled/katello.css
  ie:
    - public/stylesheets/compiled/ie.css
  contents:
    - public/stylesheets/compiled/sections/contents.css
  systems:
    - public/stylesheets/compiled/sections/systems.css
    - public/stylesheets/ui.spinner.css
    - public/stylesheets/jquery.multiselect.css
    - public/stylesheets/jquery.multiselect.filter.css
  activation_keys:
    - public/stylesheets/jquery.multiselect.css
    - public/stylesheets/jquery.multiselect.filter.css
  orgs:
    - public/stylesheets/compiled/sections/orgs.css
  subscriptions:
    - public/stylesheets/compiled/sections/subscriptions.css
  operations:
    - public/stylesheets/compiled/sections/operations.css
  dashboard:
    - public/stylesheets/compiled/sections/dashboard.css
  loginpage:
    - public/stylesheets/jquery.jnotify.css
    - public/stylesheets/jquery.jscrollpane.css
    - public/stylesheets/jquery.tipsy.css
    - public/stylesheets/compiled/sections/loginpage.css
  generic:
    - public/stylesheets/compiled/sections/generic.css
  plan:
    - public/stylesheets/jquery.timepickr.css
  fancyqueries:
    - public/stylesheets/compiled/fancyqueries.css
  tabs:
    - public/stylesheets/compiled/sections/tabs.css
  notifications:
    - public/stylesheets/compiled/sections/notifications.css
  content_search:
    - public/stylesheets/compiled/sections/content_search.css
  empty:
