# Katello configuration
#
# NOTE: This file is meant as an example. Installations via Puppet will create one properly configured in
#       /etc/katello/katello.yml
#
# :vim:sw=2:ts=2:et:

#
# Common configuration
#
# The following configuration values are the same for production, test
# and development environments. Values can be overriden bellow.
#
# host (default=127.0.0.1): The host (i.e. fully qualified domain name) of the
#   server.  This host is used by ActionMailer when generating urls sent in
#   emails from the server.  For example, the host would be the fqdn portion
#   of a URL for resetting a user's password.
#
# port: Similar to host; however, provides the port component of the URL.
#
# password_reset_expiration (default=120): Specifies the number of
#   minutes that a password reset token will remain valid.
#
common:
  warden: database
  ldap_roles: false
  use_cp: true
  use_pulp: true
  use_foreman: true
  debug_rest: false
  debug_cp_proxy: false
  debug_pulp_proxy: false
  rest_client_timeout: 30

  host: 127.0.0.1
  port: 3000
  use_ssl: false

  password_reset_expiration: 120

# Availabe language locale choices. (Note: Syntax for yaml requires a space after each comma ', ')
# Default available locales are below
# available_locales = ['de', 'en', 'es', 'fr', 'it', 'ja', 'ko', 'pt-BR', 'gu', 'hi', 'mr', 'or', 'ru', 'te', 'pa', 'kn', 'bn', 'ta', 'zh-CN', 'zh-TW']

# if you want roles permission check
# logs printed enable the following
# allow_roles_logging: true

#setup how often you want
#your notifications to be checked
#for you to receive the right notifications
#default value = 45 seconds
#
  notification:
    polling_seconds: 120

# Setup your UI search configuration.
# max_history (default=5): specifies the number of search history elements 
#   that will be retained for users
# max_favorites (default=5): specifies the number of search favorites that 
#   a user may store per search box
  search:
    max_history: 5
    max_favorites: 5

# Setup your candlepin environment here
# url: refers to the url of the candlepin
#     example https://localhost:8443/candlepin
# username: refers to admin login in candlepin
# password: refers to the admin password in candlepin
# oauth_key and oauth_secre :Specify your oauth key and secret
#   used to authenticate between Katello and Candlepin
# ca_cert_file: refers to the candlepin-ca.crt location that is needed
#   to connect to candlepin over https.This is not necessary
#   if the candlepin server is running on the same machine as katello
#   but required if the server is on a different machine. 
#   In the different machine case the katello host needs to have a 
#   copy of /etc/candlepin/certs/candlepin-ca.crt copied from 
#   the candlepin host and the location of the copied file needs to be
#   specified here.. 
  candlepin:
    url: https://localhost:8443/candlepin
    oauth_key: katello
    oauth_secret: shhhh

# Setup your pulp environment here
# url: refers to the url of the pulp
#     example https://localhost/pulp/api
# oauth_key and oauth_secre :Specify your oauth key and secret
#   used to authenticate between Katello and Pulp
# ca_cert_file: refers to the apache certificate 
#   (typically /etc/pki/tls/certs/localhost.crt) location that is needed
#   to connect to pulp over https.
  pulp:
    url: https://localhost/pulp/api
    oauth_key: katello
    oauth_secret: lmYz0oIMXBqDGp/VtMjiXWmu
    sync_threads: 4
    #sync_KBlimit: 100



# Setup your foreman environment here
# url: refers to the url of the Foreman (without the final '/')
#     example https://foreman.instance.company.com:443
# oauth_key and oauth_secre :Specify your oauth key and secret
#   used to authenticate between Katello and Foreman
  foreman:
    url: http://localhost:3001
    oauth_key: katello
    oauth_secret: shhhh
    random_password: true

  cloud_forms:
    oauth_key: cloud_forms
    oauth_secret: shhh

# Setup proxy to use when accessing CDN.
# Katello calls CDN to retrieve list of repositories for a product
# Uncomment in case you want this calls to go through your proxy
#  cdn_proxy:
#    host: localhost
#    port: 3128
#    user: username
#    password: password

#
# Production environment configuration
#
# The following configuration values override ones from the common section
#
production:
  database:
    adapter: postgresql
    username: katello
    password: katello
    database: katello
    host: localhost
    encoding: UTF8

#
# Development environment configuration
#
# The following configuration values override ones from the common section
#
development:
  foreman:
    random_password: false

#
# Test environment configuration
#
# The following configuration values override ones from the common section
#
test:

# EOF
